version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: comment_back/Dockerfile
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "comment_back.asgi:application"]
    volumes:
      - ./backend/comment_back:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=comment_back.settings
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
